ahoyapi: v2
commands:
  readme:
    usage: 'Tidy up README.md'
    cmd: |
      npx prettier README.md --write
      npx markdown-toc -i README.md

  watch:
    usage: 'Watch README.md for changes'
    cmd: |
      node watch.js
